export const quotes =
{ dog: [
    '“Outside of a dog, a book is a man’s best friend. Inside of a dog it’s too dark to read.” – Groucho Marx',
    '“My fashion philosophy is, if you’re not covered in dog hair, your life is empty.” – Elayne Boosler',
    '“No one appreciates the very special genius of your conversation as the dog does.” – Christopher Morley',
    '“Dog is God spelled backward.” – Duane Chapman',
    '“Scratch a dog and you’ll find a permanent job.” – Franklin P. Jones',
    '“A person can learn a lot from a dog: obedience, loyalty, and the importance of turning around three times before lying down.” – Robert Benchley',
    '“When a man’s best friend is his dog, that dog has a problem.” – Edward Abbey',
    '“Dogs have boundless enthusiasm but no sense of shame. I should have a dog as a life coach.” – Moby',
    '“You want a friend in Washington? Get a dog.” – Harry S Truman',
    '“The dog is the god of frolic.” – Henry Ward Beecher',
    '“Anybody who doesn’t know what soap tastes like never washed a dog.” – Franklin P. Jones',
    '“What do dogs do on their day off? Can’t lie around – that’s their job.” – George Carlin',
    '“I don’t understand people who don’t touch their pets. Their cat or dog is called a pet for a reason.” – Jarod Kintz',
    '“If you don’t own a dog, at least one, there is not necessarily anything wrong with you, but there may be something wrong with your life.” – Roger A. Caras',
    '“All his life he tried to be a good person. Many times, however, he failed. For after all, he was only human. He wasn’t a dog.” – Charles M Schulz',
    '“I like dogs. You always know what a dog is thinking. It has four moods. Happy, sad, cross, and concentrating. Also, dogs are faithful and they do not tell lies because they cannot talk.” – Mark Haddon',
    '“I’ve seen a look in dogs’ eyes, a quickly vanishing look of amazed contempt, and I am convinced that basically dogs think humans are nuts.” – John Steinbeck',
    '“Dogs never talk about themselves but listen to you while you talk about yourself, and keep up an appearance of being interested in the conversation.” – Jerome K. Jerome',
    '“A dog is the only thing on earth that loves you more than you love yourself.” – Josh Billings',
    '“No matter how you’re feeling, a little dog gonna love you.” – Waka Flocka Flame',
    '“There’s a saying. If you want someone to love you forever, buy a dog, feed it and keep it around.” – Dick Dale',
    '“When the dog looks at you, the dog is not thinking what kind of a person you are. The dog is not judging you.” – Eckhart Tolle',
    '“The great pleasure of a dog is that you may make a fool of yourself with him and not only will he not scold you, but he will make a fool of himself too.” – Samuel Butler',
    '“Actually, my dog I think is the only person who consistently loves me all the time.” – H. G. Bissinger',
    '“Such short little lives our pets have to spend with us, and they spend most of it waiting for us to come home each day.” – John Grogan',
    '“There is no faith which has never yet been broken, except that of a truly faithful dog” – Konrad Lorenz',
    '“If you pick up a starving dog and make him prosperous he will not bite you. This is the principal difference between a dog and man.” – Mark Twain',
    '“Money can buy you a fine dog, but only love can make him wag his tail.” – Kinky Friedman',
    '“The dog is the perfect portrait subject. He doesn’t pose. He isn’t aware of the camera.” – Patrick Demarchelier',
    '“It’s not the size of the dog in the fight, it’s the size of the fight in the dog.” – Mark Twain',
    '“The love of a dog is a pure thing. He gives you a trust which is total. You must not betray it.” – Michel Houellebecq',
    '“You know, a dog can snap you out of any kind of bad mood that you’re in faster than you can think of.” – Jill Abramson',
    '“My favorite type of pet has always been a dog. They’re loyal, kind, and offer endless affection. My friend Eric says, ‘The more people I meet, the more I like my dog.’ Funny thought.” – Brendon Urie',
    '“You can tell by the kindness of a dog how a human should be.” – Captain Beefheart',
    '“The dog lives for the day, the hour, even the moment.” – Robert Falcon Scott',
    '“Every dog must have his day.” – Jonathan Swift',
    '“Dogs do speak, but only to those who know how to listen.”– Orhan Pamuk',
    '“You can usually tell that a man is good if he has a dog who loves him.” – W. Bruce Cameron',
    '“I think dogs are the most amazing creatures; they give unconditional love. For me, they are the role model for being alive.” – Gilda Radner',
    '“A dog will teach you unconditional love. If you can have that in your life, things won’t be too bad.” – Robert Wagner',
    '“The bond with a true dog is as lasting as the ties of this earth will ever be.” – Konrad Lorenz',
    '“Before you get a dog, you can’t quite imagine what living with one might be like; afterward, you can’t imagine living any other way.” – Caroline Knapp',
    '“Fall in love with a dog, and in many ways you enter a new orbit, a universe that features not just new colors but new rituals, new rules, a new way of experiencing attachment.” – Caroline Knapp',
    '“Everybody should have a shelter dog. It’s good for the soul.” – Paul Shaffer',
    '“The poor dog, in life the firmest friend. The first to welcome, foremost to defend.” – Lord Byron',
    '“The dog is a gentleman; I hope to go to his heaven not man’s.” – Mark Twain',
    '“It is amazing how much love and laughter they bring into our lives and even how much closer we become with each other because of them.” – John Grogan',
    '“Petting, scratching, and cuddling a dog could be as soothing to the mind and heart as deep meditation and almost as good for the soul as prayer.” – Dean Koontz',
    '“It’s just the most amazing thing to love a dog, isn’t it? It makes our relationships with people seem as boring as a bowl of oatmeal.” – John Grogan',
    '“Dogs are not our whole life, but they make our lives whole.” – Roger Caras',
    '“Did you know that there are over 300 words for love in canine?” – Gabriel Zevin',
    '“All you need is love and a dog.” – Unknown',
    '“Live. Laugh. Bark.” – Unknown',
    '“Keep calm and pet a dog.” – Unknown',
    '“My dog thinks I’m a catch.” – Unknown',
    '“Everyone thinks they have the best dog, and none of them are wrong.” – Unknown',
    '“Love is a four-legged word.” – Unknown',
    '“Life is too short to just have one dog.” – Unknown',
    '“My little dog – a heartbeat at my feet.” – Edith Wharton',
    '“Happiness is a warm puppy.” – Charles Shultz',
    '“A dog may be man’s best friend, but a child’s best friend is a puppy.” – Unknown',
    '“The best way to get a puppy is to beg for a baby brother– and they’ll settle for a puppy every time.” – Winston Pendleton',
    '“It’s impossible to keep a straight face in the presence of one or more puppies.” – Unknown',
    '“Puppies are nature’s remedy for feeling unloved, plus numerous other ailments of life.” – Richard Allen Palm',
    '“Whoever said you can’t buy happiness forgot little puppies.” – Gene Hill',
    '“If it wasn’t for puppies, some people would never go for a walk.” – Unknown',
  ]
};
